@echo off
echo Building misc.vpp_pc...
Gibbed.Volition.Pack.exe "misc.vpp_pc" "data\modding\misc" "data\original\misc"
echo Creating items_containers.asm_pc...
Gibbed.Volition.ConvertAsm.exe -o -xml2asm "data\source\items_containers.xml" "data\modding\items\items_containers.asm_pc"
echo Building items.vpp_pc...
Gibbed.Volition.Pack.exe "items.vpp_pc" "data\modding\items" "data\original\items"
echo Creating vfx_containers.asm_pc...
Gibbed.Volition.ConvertAsm.exe -o -xml2asm "data\source\vfx_containers.xml" "data\modding\effects\vfx_containers.asm_pc"
echo Building effects.vpp_pc...
Gibbed.Volition.Pack.exe "effects.vpp_pc" "data\modding\effects" "data\original\effects"
echo All done!
pause